# Generated by Django 5.0.6 on 2024-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("items_sold", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField()),
                ("link", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
