# Generated by Django 5.0.6 on 2024-06-15 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_pricetrackerusers_scrapeditem_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PriceTrackerUsers",
            new_name="PriceTrackerUser",
        ),
    ]
