# Generated by Django 5.0.6 on 2024-06-15 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_pricetrackeruser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricetrackeruser",
            name="username",
        ),
    ]
