# Generated by Django 5.0.6 on 2024-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_scrapeditem_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapeditem",
            name="link",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
