# Generated by Django 5.0.6 on 2024-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_scrapeditem_url_alter_scrapeditem_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapeditem",
            name="link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="scrapeditem",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
