# Generated by Django 5.0.6 on 2024-06-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_pricetrackerusers_pricetrackeruser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapeditem",
            name="owner",
        ),
        migrations.AddField(
            model_name="scrapeditem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.pricetrackeruser",
            ),
        ),
    ]
