# Generated by Django 5.0.6 on 2024-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_remove_scrapeditem_owner_scrapeditem_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricetrackeruser",
            name="name",
        ),
        migrations.AddField(
            model_name="pricetrackeruser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pricetrackeruser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
