# Generated by Django 5.0.6 on 2024-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_pricetrackeruser_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricetrackeruser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
