# Generated by Django 5.0.6 on 2024-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_alter_scrapeditem_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapeditem",
            name="url",
            field=models.URLField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="scrapeditem",
            name="link",
            field=models.URLField(default="", max_length=1000),
        ),
    ]
